require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - ".git/**/*"
    - "bin/*"
    - "config/**/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config.ru"
    - "Rakefile"
  TargetRubyVersion: 3.3.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
